export interface Country {
  name: string
  slug: string
  flag: string
  phoneCode: string
  region: "european-blue-card" | "europe-other" | "north-america" | "gcc" | "oceania"
  description: string
  highlights: string[]
  visaType: string
  officialName: string
  capital: string
  officialLanguages: string[]
  population: number
  area: number
  currency: string
}

export const euCountries: Country[] = [
  {
    name: "Luxembourg",
    slug: "luxembourg",
    flag: "https://flagcdn.com/lu.svg",
    phoneCode: "+352",
    region: "european-blue-card",
    description: "Le Luxembourg offre une Carte Bleue Européenne avec des conditions attractives pour les professionnels qualifiés. Centre financier de l'Europe avec une qualité de vie exceptionnelle.",
    highlights: ["Salaire minimum élevé", "Multilinguisme", "Centre financier européen", "Qualité de vie exceptionnelle"],
    visaType: "Carte Bleue Européenne",
    officialName: "Grand-Duché de Luxembourg",
    capital: "Luxembourg",
    officialLanguages: ["Luxembourgeois", "Français", "Allemand"],
    population: 0.65,
    area: 2586,
    currency: "Euro"
  },
  {
    name: "Belgique",
    slug: "belgium",
    flag: "https://flagcdn.com/be.svg",
    phoneCode: "+32",
    region: "european-blue-card",
    description: "La Belgique propose une Carte Bleue Européenne pour les travailleurs hautement qualifiés. Située au cœur de l'Europe avec accès aux institutions européennes.",
    highlights: ["Capitale de l'UE", "Système de santé excellent", "Position centrale en Europe", "Diversité culturelle"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume de Belgique",
    capital: "Bruxelles",
    officialLanguages: ["Néerlandais", "Français", "Allemand"],
    population: 11.7,
    area: 30528,
    currency: "Euro"
  },
  {
    name: "Allemagne",
    slug: "germany",
    flag: "https://flagcdn.com/de.svg",
    phoneCode: "+49",
    region: "european-blue-card",
    description: "L'Allemagne est la première économie européenne et offre d'excellentes opportunités pour les professionnels qualifiés avec sa Carte Bleue Européenne.",
    highlights: ["Première économie européenne", "Industrie technologique avancée", "Excellentes infrastructures", "Forte demande de talents"],
    visaType: "Carte Bleue Européenne",
    officialName: "République fédérale d'Allemagne",
    capital: "Berlin",
    officialLanguages: ["Allemand"],
    population: 83.3,
    area: 357022,
    currency: "Euro"
  },
  {
    name: "Autriche",
    slug: "austria",
    flag: "https://flagcdn.com/at.svg",
    phoneCode: "+43",
    region: "european-blue-card",
    description: "L'Autriche offre une excellente qualité de vie et des opportunités professionnelles dans un cadre alpin magnifique.",
    highlights: ["Qualité de vie élevée", "Cadre naturel exceptionnel", "Économie stable", "Culture riche"],
    visaType: "Carte Bleue Européenne",
    officialName: "République d'Autriche",
    capital: "Vienne",
    officialLanguages: ["Allemand"],
    population: 9.1,
    area: 83871,
    currency: "Euro"
  },
  {
    name: "Pays-Bas",
    slug: "netherlands",
    flag: "https://flagcdn.com/nl.svg",
    phoneCode: "+31",
    region: "european-blue-card",
    description: "Les Pays-Bas sont reconnus pour leur ouverture internationale et leur écosystème startup dynamique.",
    highlights: ["Hub technologique européen", "Population anglophone", "Écosystème startup", "Infrastructure cyclable"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume des Pays-Bas",
    capital: "Amsterdam",
    officialLanguages: ["Néerlandais"],
    population: 17.8,
    area: 41543,
    currency: "Euro"
  },
  {
    name: "Suède",
    slug: "sweden",
    flag: "https://flagcdn.com/se.svg",
    phoneCode: "+46",
    region: "european-blue-card",
    description: "La Suède offre un équilibre travail-vie personnelle exemplaire et une forte culture d'innovation.",
    highlights: ["Équilibre vie-travail", "Innovation technologique", "Congés parentaux généreux", "Nature préservée"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume de Suède",
    capital: "Stockholm",
    officialLanguages: ["Suédois"],
    population: 10.5,
    area: 450295,
    currency: "Couronne suédoise"
  },
  {
    name: "Finlande",
    slug: "finland",
    flag: "https://flagcdn.com/fi.svg",
    phoneCode: "+358",
    region: "european-blue-card",
    description: "La Finlande est régulièrement classée parmi les pays les plus heureux au monde avec un excellent système éducatif.",
    highlights: ["Pays le plus heureux", "Éducation excellente", "Technologie avancée", "Nature sauvage"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Finlande",
    capital: "Helsinki",
    officialLanguages: ["Finnois", "Suédois"],
    population: 5.5,
    area: 338145,
    currency: "Euro"
  },
  {
    name: "Malte",
    slug: "malta",
    flag: "https://flagcdn.com/mt.svg",
    phoneCode: "+356",
    region: "european-blue-card",
    description: "Malte offre un climat méditerranéen agréable et un secteur des services financiers et du gaming en pleine croissance.",
    highlights: ["Climat méditerranéen", "Anglais langue officielle", "Secteur iGaming", "Fiscalité avantageuse"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Malte",
    capital: "La Valette",
    officialLanguages: ["Maltais", "Anglais"],
    population: 0.53,
    area: 316,
    currency: "Euro"
  },
  {
    name: "Italie",
    slug: "italy",
    flag: "https://flagcdn.com/it.svg",
    phoneCode: "+39",
    region: "european-blue-card",
    description: "L'Italie combine richesse culturelle et opportunités dans les secteurs de la mode, du design et de la technologie.",
    highlights: ["Patrimoine culturel", "Design et mode", "Gastronomie", "Art de vivre"],
    visaType: "Carta Blu UE",
    officialName: "République italienne",
    capital: "Rome",
    officialLanguages: ["Italien"],
    population: 58.9,
    area: 301340,
    currency: "Euro"
  },
  {
    name: "Espagne",
    slug: "spain",
    flag: "https://flagcdn.com/es.svg",
    phoneCode: "+34",
    region: "european-blue-card",
    description: "L'Espagne offre un excellent climat, une riche culture et des opportunités croissantes dans la tech.",
    highlights: ["Climat ensoleillé", "Qualité de vie", "Coût de vie raisonnable", "Hubs tech émergents"],
    visaType: "Tarjeta Azul UE",
    officialName: "Royaume d'Espagne",
    capital: "Madrid",
    officialLanguages: ["Espagnol"],
    population: 48.1,
    area: 505990,
    currency: "Euro"
  },
  {
    name: "Portugal",
    slug: "portugal",
    flag: "https://flagcdn.com/pt.svg",
    phoneCode: "+351",
    region: "european-blue-card",
    description: "Le Portugal attire les professionnels avec son climat doux, sa qualité de vie et son écosystème tech en croissance.",
    highlights: ["Climat agréable", "Coût de vie attractif", "Communauté expat", "Écosystème startup"],
    visaType: "Cartão Azul UE",
    officialName: "République portugaise",
    capital: "Lisbonne",
    officialLanguages: ["Portugais"],
    population: 10.5,
    area: 92212,
    currency: "Euro"
  },
  {
    name: "Bulgarie",
    slug: "bulgaria",
    flag: "https://flagcdn.com/bg.svg",
    phoneCode: "+359",
    region: "european-blue-card",
    description: "La Bulgarie offre un coût de vie bas et des opportunités croissantes dans le secteur IT.",
    highlights: ["Coût de vie bas", "Secteur IT en croissance", "Nature diverse", "Fiscalité attractive"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Bulgarie",
    capital: "Sofia",
    officialLanguages: ["Bulgare"],
    population: 6.4,
    area: 110994,
    currency: "Lev bulgare"
  },
  {
    name: "Chypre",
    slug: "cyprus",
    flag: "https://flagcdn.com/cy.svg",
    phoneCode: "+357",
    region: "european-blue-card",
    description: "Chypre combine climat méditerranéen et opportunités dans les services financiers.",
    highlights: ["Climat méditerranéen", "Services financiers", "Anglais répandu", "Qualité de vie"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Chypre",
    capital: "Nicosie",
    officialLanguages: ["Grec", "Turc"],
    population: 1.2,
    area: 9251,
    currency: "Euro"
  },
  {
    name: "Croatie",
    slug: "croatia",
    flag: "https://flagcdn.com/hr.svg",
    phoneCode: "+385",
    region: "european-blue-card",
    description: "La Croatie offre un cadre de vie exceptionnel avec sa côte adriatique et son intégration récente à l'UE.",
    highlights: ["Côte adriatique", "Membre récent de l'UE", "Tourisme développé", "Qualité de vie"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Croatie",
    capital: "Zagreb",
    officialLanguages: ["Croate"],
    population: 3.8,
    area: 56594,
    currency: "Euro"
  },
  {
    name: "Estonie",
    slug: "estonia",
    flag: "https://flagcdn.com/ee.svg",
    phoneCode: "+372",
    region: "european-blue-card",
    description: "L'Estonie est pionnière en e-gouvernement et offre un écosystème startup dynamique.",
    highlights: ["E-gouvernement avancé", "Écosystème startup", "Société numérique", "E-résidence"],
    visaType: "Carte Bleue Européenne",
    officialName: "République d'Estonie",
    capital: "Tallinn",
    officialLanguages: ["Estonien"],
    population: 1.36,
    area: 45227,
    currency: "Euro"
  },
  {
    name: "France",
    slug: "france",
    flag: "https://flagcdn.com/fr.svg",
    phoneCode: "+33",
    region: "european-blue-card",
    description: "La France offre une économie diversifiée, une culture riche et un excellent système de protection sociale.",
    highlights: ["Culture riche", "Système de santé", "Gastronomie", "Hubs tech (Paris, Lyon)"],
    visaType: "Carte Bleue Européenne",
    officialName: "République française",
    capital: "Paris",
    officialLanguages: ["Français"],
    population: 68.0,
    area: 551695,
    currency: "Euro"
  },
  {
    name: "Grèce",
    slug: "greece",
    flag: "https://flagcdn.com/gr.svg",
    phoneCode: "+30",
    region: "european-blue-card",
    description: "La Grèce combine patrimoine historique exceptionnel et qualité de vie méditerranéenne.",
    highlights: ["Patrimoine historique", "Climat méditerranéen", "Coût de vie modéré", "Tourisme"],
    visaType: "Carte Bleue Européenne",
    officialName: "République hellénique",
    capital: "Athènes",
    officialLanguages: ["Grec"],
    population: 10.4,
    area: 131957,
    currency: "Euro"
  },
  {
    name: "Hongrie",
    slug: "hungary",
    flag: "https://flagcdn.com/hu.svg",
    phoneCode: "+36",
    region: "european-blue-card",
    description: "La Hongrie offre un coût de vie attractif et une position centrale en Europe.",
    highlights: ["Coût de vie bas", "Position centrale", "Architecture", "Thermes"],
    visaType: "Carte Bleue Européenne",
    officialName: "Hongrie",
    capital: "Budapest",
    officialLanguages: ["Hongrois"],
    population: 9.6,
    area: 93028,
    currency: "Forint hongrois"
  },
  {
    name: "Lettonie",
    slug: "latvia",
    flag: "https://flagcdn.com/lv.svg",
    phoneCode: "+371",
    region: "european-blue-card",
    description: "La Lettonie offre un écosystème startup en développement et une qualité de vie nordique.",
    highlights: ["Startup ecosystem", "Nature baltique", "Coût de vie modéré", "IT en croissance"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Lettonie",
    capital: "Riga",
    officialLanguages: ["Letton"],
    population: 1.88,
    area: 64589,
    currency: "Euro"
  },
  {
    name: "Lituanie",
    slug: "lithuania",
    flag: "https://flagcdn.com/lt.svg",
    phoneCode: "+370",
    region: "european-blue-card",
    description: "La Lituanie est reconnue pour son secteur fintech et sa qualité de vie.",
    highlights: ["Hub fintech", "Qualité de vie", "Internet rapide", "Coût de vie modéré"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Lituanie",
    capital: "Vilnius",
    officialLanguages: ["Lituanien"],
    population: 2.8,
    area: 65300,
    currency: "Euro"
  },
  {
    name: "Pologne",
    slug: "poland",
    flag: "https://flagcdn.com/pl.svg",
    phoneCode: "+48",
    region: "european-blue-card",
    description: "La Pologne offre une économie dynamique et un secteur IT en pleine expansion.",
    highlights: ["Économie dynamique", "Secteur IT", "Coût de vie modéré", "Villes historiques"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Pologne",
    capital: "Varsovie",
    officialLanguages: ["Polonais"],
    population: 36.8,
    area: 312696,
    currency: "Złoty"
  },
  {
    name: "République tchèque",
    slug: "czech-republic",
    flag: "https://flagcdn.com/cz.svg",
    phoneCode: "+420",
    region: "european-blue-card",
    description: "La République tchèque combine patrimoine culturel et économie industrielle avancée.",
    highlights: ["Prague", "Industrie automobile", "Coût de vie", "Position centrale"],
    visaType: "Carte Bleue Européenne",
    officialName: "République tchèque",
    capital: "Prague",
    officialLanguages: ["Tchèque"],
    population: 10.8,
    area: 78867,
    currency: "Couronne tchèque"
  },
  {
    name: "Roumanie",
    slug: "romania",
    flag: "https://flagcdn.com/ro.svg",
    phoneCode: "+40",
    region: "european-blue-card",
    description: "La Roumanie offre un secteur IT compétitif et un coût de vie attractif.",
    highlights: ["Secteur IT fort", "Coût de vie bas", "Francophonie", "Nature diverse"],
    visaType: "Carte Bleue Européenne",
    officialName: "Roumanie",
    capital: "Bucarest",
    officialLanguages: ["Roumain"],
    population: 19.0,
    area: 238391,
    currency: "Leu roumain"
  },
  {
    name: "Slovaquie",
    slug: "slovakia",
    flag: "https://flagcdn.com/sk.svg",
    phoneCode: "+421",
    region: "european-blue-card",
    description: "La Slovaquie offre une position centrale en Europe et une industrie automobile développée.",
    highlights: ["Industrie automobile", "Position centrale", "Coût de vie modéré", "Nature"],
    visaType: "Carte Bleue Européenne",
    officialName: "République slovaque",
    capital: "Bratislava",
    officialLanguages: ["Slovaque"],
    population: 5.4,
    area: 49035,
    currency: "Euro"
  },
  {
    name: "Slovénie",
    slug: "slovenia",
    flag: "https://flagcdn.com/si.svg",
    phoneCode: "+386",
    region: "european-blue-card",
    description: "La Slovénie combine qualité de vie alpine et accès méditerranéen.",
    highlights: ["Nature alpine", "Qualité de vie", "Taille humaine", "Accès Adriatique"],
    visaType: "Carte Bleue Européenne",
    officialName: "République de Slovénie",
    capital: "Ljubljana",
    officialLanguages: ["Slovène"],
    population: 2.1,
    area: 20273,
    currency: "Euro"
  },
]

export const northAmericaCountries: Country[] = [
  {
    name: "Canada",
    slug: "canada",
    flag: "https://flagcdn.com/ca.svg",
    phoneCode: "+1",
    region: "north-america",
    description: "Le Canada offre des programmes d'immigration variés avec une politique d'accueil reconnue mondialement.",
    highlights: ["Entrée Express", "PNP (Programmes provinciaux)", "Qualité de vie élevée", "Multiculturalisme"],
    visaType: "Résidence Permanente",
    officialName: "Canada",
    capital: "Ottawa",
    officialLanguages: ["Anglais", "Français"],
    population: 40.0,
    area: 9984670,
    currency: "Dollar canadien"
  },
  {
    name: "États-Unis",
    slug: "united-states",
    flag: "https://flagcdn.com/us.svg",
    phoneCode: "+1",
    region: "north-america",
    description: "Les États-Unis offrent diverses catégories de visas pour les professionnels qualifiés.",
    highlights: ["Visa H-1B", "Visa O-1", "Green Card par emploi", "Opportunités Silicon Valley"],
    visaType: "H-1B / Green Card",
    officialName: "États-Unis d'Amérique",
    capital: "Washington, D.C.",
    officialLanguages: ["Anglais"],
    population: 334.9,
    area: 9833517,
    currency: "Dollar américain"
  },
]

export const gccCountries: Country[] = [
  {
    name: "Émirats Arabes Unis",
    slug: "united-arab-emirates",
    flag: "https://flagcdn.com/ae.svg",
    phoneCode: "+971",
    region: "gcc",
    description: "Les EAU offrent des opportunités exceptionnelles à Dubaï et Abu Dhabi avec des salaires attractifs.",
    highlights: ["Pas d'impôt sur le revenu", "Dubaï hub mondial", "Golden Visa", "Infrastructure moderne"],
    visaType: "Visa de Travail / Golden Visa",
    officialName: "Émirats arabes unis",
    capital: "Abou Dabi",
    officialLanguages: ["Arabe"],
    population: 9.4,
    area: 83600,
    currency: "Dirham des Émirats arabes unis"
  },
  {
    name: "Qatar",
    slug: "qatar",
    flag: "https://flagcdn.com/qa.svg",
    phoneCode: "+974",
    region: "gcc",
    description: "Le Qatar offre des salaires compétitifs et des projets ambitieux dans divers secteurs.",
    highlights: ["Salaires élevés", "Projets d'infrastructure", "Pas d'impôt", "Qualité de vie"],
    visaType: "Visa de Travail",
    officialName: "État du Qatar",
    capital: "Doha",
    officialLanguages: ["Arabe"],
    population: 2.7,
    area: 11586,
    currency: "Riyal qatari"
  },
  {
    name: "Koweït",
    slug: "kuwait",
    flag: "https://flagcdn.com/kw.svg",
    phoneCode: "+965",
    region: "gcc",
    description: "Le Koweït offre des opportunités dans le secteur pétrolier et les services.",
    highlights: ["Secteur pétrolier", "Salaires compétitifs", "Pas d'impôt", "Allocations logement"],
    visaType: "Visa de Travail",
    officialName: "État du Koweït",
    capital: "Koweït",
    officialLanguages: ["Arabe"],
    population: 4.3,
    area: 17818,
    currency: "Dinar koweïtien"
  },
  {
    name: "Bahreïn",
    slug: "bahrain",
    flag: "https://flagcdn.com/bh.svg",
    phoneCode: "+973",
    region: "gcc",
    description: "Bahreïn est un centre financier régional avec un environnement business favorable.",
    highlights: ["Centre financier", "Flexi Permit", "Taille humaine", "Diversité économique"],
    visaType: "Visa de Travail / Flexi Permit",
    officialName: "Royaume de Bahreïn",
    capital: "Manama",
    officialLanguages: ["Arabe"],
    population: 1.5,
    area: 765,
    currency: "Dinar bahreïni"
  },
  {
    name: "Oman",
    slug: "oman",
    flag: "https://flagcdn.com/om.svg",
    phoneCode: "+968",
    region: "gcc",
    description: "Oman offre un cadre de vie paisible et des opportunités dans le tourisme et l'énergie.",
    highlights: ["Cadre paisible", "Tourisme en développement", "Secteur énergétique", "Culture authentique"],
    visaType: "Visa de Travail",
    officialName: "Sultanat d'Oman",
    capital: "Mascate",
    officialLanguages: ["Arabe"],
    population: 4.6,
    area: 309500,
    currency: "Rial omanais"
  },
  {
    name: "Arabie Saoudite",
    slug: "saudi-arabia",
    flag: "https://flagcdn.com/sa.svg",
    phoneCode: "+966",
    region: "gcc",
    description: "L'Arabie Saoudite offre des opportunités majeures avec la Vision 2030 et des mégaprojets.",
    highlights: ["Vision 2030", "Mégaprojets (NEOM)", "Salaires élevés", "Pas d'impôt sur le revenu"],
    visaType: "Visa de Travail / Iqama",
    officialName: "Royaume d'Arabie saoudite",
    capital: "Riyad",
    officialLanguages: ["Arabe"],
    population: 36.4,
    area: 2149690,
    currency: "Riyal saoudien"
  },
]

export const oceaniaCountries: Country[] = [
  {
    name: "Australie",
    slug: "australia",
    flag: "https://flagcdn.com/au.svg",
    phoneCode: "+61",
    region: "oceania",
    description: "L'Australie offre une excellente qualité de vie et un système d'immigration par points.",
    highlights: ["Skilled Independent Visa", "Qualité de vie", "Économie stable", "Nature exceptionnelle"],
    visaType: "Visa Qualifié (189/190/491)",
    officialName: "Commonwealth d'Australie",
    capital: "Canberra",
    officialLanguages: ["Anglais"],
    population: 26.6,
    area: 7692024,
    currency: "Dollar australien"
  },
  {
    name: "Nouvelle-Zélande",
    slug: "new-zealand",
    flag: "https://flagcdn.com/nz.svg",
    phoneCode: "+64",
    region: "oceania",
    description: "La Nouvelle-Zélande offre un cadre de vie exceptionnel et des opportunités pour les professionnels qualifiés.",
    highlights: ["Skilled Migrant Category", "Équilibre vie-travail", "Nature préservée", "Société accueillante"],
    visaType: "Skilled Migrant Category",
    officialName: "Nouvelle-Zélande",
    capital: "Wellington",
    officialLanguages: ["Anglais", "Māori"],
    population: 5.2,
    area: 268021,
    currency: "Dollar néo-zélandais"
  },
]

export const europeOtherCountries: Country[] = [
  {
    name: "Danemark",
    slug: "denmark",
    flag: "https://flagcdn.com/dk.svg",
    phoneCode: "+45",
    region: "europe-other",
    description: "Le Danemark est reconnu pour son équilibre vie-travail et son économie innovante.",
    highlights: ["Équilibre vie-travail", "Design danois", "Vélo culture", "Innovation verte"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume du Danemark",
    capital: "Copenhague",
    officialLanguages: ["Danois"],
    population: 5.9,
    area: 42933,
    currency: "Couronne danoise"
  },
  {
    name: "Irlande",
    slug: "ireland",
    flag: "https://flagcdn.com/ie.svg",
    phoneCode: "+353",
    region: "europe-other",
    description: "L'Irlande est un hub technologique majeur avec de nombreuses multinationales.",
    highlights: ["Hub tech européen", "Anglophone", "Multinationales", "Culture accueillante"],
    visaType: "Carte Bleue Européenne",
    officialName: "Irlande",
    capital: "Dublin",
    officialLanguages: ["Irlandais", "Anglais"],
    population: 5.3,
    area: 70273,
    currency: "Euro"
  },
  {
    name: "Suisse",
    slug: "switzerland",
    flag: "https://flagcdn.com/ch.svg",
    phoneCode: "+41",
    region: "europe-other",
    description: "La Suisse est reconnue pour sa stabilité économique, ses salaires élevés et son cadre de vie premium.",
    highlights: ["Salaires élevés", "Pays multilingue", "Infrastructure de qualité", "Sécurité"],
    visaType: "Carte Bleue Européenne",
    officialName: "Confédération suisse",
    capital: "Berne",
    officialLanguages: ["Allemand", "Français", "Italien", "Romanche"],
    population: 8.8,
    area: 41285,
    currency: "Franc suisse"
  },
  {
    name: "Norvège",
    slug: "norway",
    flag: "https://flagcdn.com/no.svg",
    phoneCode: "+47",
    region: "europe-other",
    description: "La Norvège offre une excellente qualité de vie, un système social solide et des secteurs énergétiques dynamiques.",
    highlights: ["Qualité de vie élevée", "Nature spectaculaire", "Économie stable", "Système social fort"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume de Norvège",
    capital: "Oslo",
    officialLanguages: ["Norvégien"],
    population: 5.5,
    area: 385207,
    currency: "Couronne norvégienne"
  },
  {
    name: "Islande",
    slug: "iceland",
    flag: "https://flagcdn.com/is.svg",
    phoneCode: "+354",
    region: "europe-other",
    description: "L'Islande est idéale pour les professionnels qui recherchent un environnement innovant, durable et une nature préservée.",
    highlights: ["Durabilité", "Innovation", "Cadre naturel unique", "Petite communauté internationale"],
    visaType: "Carte Bleue Européenne",
    officialName: "Islande",
    capital: "Reykjavik",
    officialLanguages: ["Islandais"],
    population: 0.38,
    area: 103000,
    currency: "Couronne islandaise"
  },
  {
    name: "Royaume-Uni",
    slug: "united-kingdom",
    flag: "https://flagcdn.com/gb.svg",
    phoneCode: "+44",
    region: "europe-other",
    description: "Le Royaume-Uni reste une destination majeure pour les professionnels qualifiés, avec un marché du travail international et de nombreuses opportunités.",
    highlights: ["Marché du travail international", "Centres financiers mondiaux", "Diversité culturelle", "Réseaux professionnels"],
    visaType: "Carte Bleue Européenne",
    officialName: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
    capital: "Londres",
    officialLanguages: ["Anglais"],
    population: 67.3,
    area: 242495,
    currency: "Livre sterling"
  }
]

export const allCountries = [...euCountries, ...europeOtherCountries, ...northAmericaCountries, ...gccCountries, ...oceaniaCountries]

export function getCountryBySlug(slug: string): Country | undefined {
  return allCountries.find(country => country.slug === slug)
}

export function getCountriesByRegion(region: Country["region"]): Country[] {
  return allCountries.filter(country => country.region === region)
}
